//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ABONNÉS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ABONNÉS()
        {
            this.EMPRUNTER = new HashSet<EMPRUNTER>();
        }
    
        public int CODE_ABONNÉ { get; set; }
        public Nullable<int> CODE_PAYS { get; set; }
        public string NOM_ABONNÉ { get; set; }
        public string PRÉNOM_ABONNÉ { get; set; }
        public string LOGIN_ABONNÉ { get; set; }
        public string PASSWORD_ABONNÉ { get; set; }
        public bool isAdmin { get; set; }
        public System.DateTime creationDate { get; set; }
    
        public virtual PAYS PAYS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPRUNTER> EMPRUNTER { get; set; }
    }
}
