//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALBUMS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ALBUMS()
        {
            this.EMPRUNTER = new HashSet<EMPRUNTER>();
        }
    
        public int CODE_ALBUM { get; set; }
        public Nullable<int> CODE_EDITEUR { get; set; }
        public Nullable<int> CODE_GENRE { get; set; }
        public string TITRE_ALBUM { get; set; }
        public Nullable<int> ANNÉE_ALBUM { get; set; }
        public decimal PRIX_ALBUM { get; set; }
        public string ALLÉE_ALBUM { get; set; }
        public int CASIER_ALBUM { get; set; }
        public byte[] POCHETTE { get; set; }
    
        public virtual EDITEURS EDITEURS { get; set; }
        public virtual GENRES GENRES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPRUNTER> EMPRUNTER { get; set; }
    }
}
