
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EF_MAJ_CHAMPIONNAT
{

using System;
    using System.Collections.Generic;
    
public partial class EQUIPES
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public EQUIPES()
    {

        this.JOUEURS = new HashSet<JOUEURS>();

        this.RENCONTRES = new HashSet<RENCONTRES>();

        this.RENCONTRES1 = new HashSet<RENCONTRES>();

    }


    public int ID_EQUIPE { get; set; }

    public string VILLE { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<JOUEURS> JOUEURS { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<RENCONTRES> RENCONTRES { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<RENCONTRES> RENCONTRES1 { get; set; }

}

}
