

//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EF_MAJ_CHAMPIONNAT
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

using System.Data.Entity.Core.Objects;
using System.Linq;


public partial class CHAMPIONNATEntities : DbContext
{
    public CHAMPIONNATEntities()
        : base("name=CHAMPIONNATEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<EQUIPES> EQUIPES { get; set; }

    public virtual DbSet<JOUEURS> JOUEURS { get; set; }

    public virtual DbSet<RENCONTRES> RENCONTRES { get; set; }


    public virtual int AfficheInfosJoueur(Nullable<int> idJoueur)
    {

        var idJoueurParameter = idJoueur.HasValue ?
            new ObjectParameter("IdJoueur", idJoueur) :
            new ObjectParameter("IdJoueur", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AfficheInfosJoueur", idJoueurParameter);
    }


    public virtual ObjectResult<AfficheJoueur_Result> AfficheJoueur(Nullable<int> num)
    {

        var numParameter = num.HasValue ?
            new ObjectParameter("Num", num) :
            new ObjectParameter("Num", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AfficheJoueur_Result>("AfficheJoueur", numParameter);
    }


    public virtual ObjectResult<InsertEquipe_Result> InsertEquipe(string ville)
    {

        var villeParameter = ville != null ?
            new ObjectParameter("Ville", ville) :
            new ObjectParameter("Ville", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<InsertEquipe_Result>("InsertEquipe", villeParameter);
    }


    public virtual int InsertJoueur(string nom, Nullable<int> numEquipe, Nullable<int> salaire)
    {

        var nomParameter = nom != null ?
            new ObjectParameter("Nom", nom) :
            new ObjectParameter("Nom", typeof(string));


        var numEquipeParameter = numEquipe.HasValue ?
            new ObjectParameter("NumEquipe", numEquipe) :
            new ObjectParameter("NumEquipe", typeof(int));


        var salaireParameter = salaire.HasValue ?
            new ObjectParameter("Salaire", salaire) :
            new ObjectParameter("Salaire", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertJoueur", nomParameter, numEquipeParameter, salaireParameter);
    }


    public virtual int ListeRencontresParEquipe()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ListeRencontresParEquipe");
    }


    public virtual ObjectResult<ModifieSalaire_Result> ModifieSalaire(Nullable<int> idJoueur, Nullable<int> newSalaire)
    {

        var idJoueurParameter = idJoueur.HasValue ?
            new ObjectParameter("IdJoueur", idJoueur) :
            new ObjectParameter("IdJoueur", typeof(int));


        var newSalaireParameter = newSalaire.HasValue ?
            new ObjectParameter("NewSalaire", newSalaire) :
            new ObjectParameter("NewSalaire", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ModifieSalaire_Result>("ModifieSalaire", idJoueurParameter, newSalaireParameter);
    }


    public virtual ObjectResult<RencontresDuneEquipe_Result> RencontresDuneEquipe(Nullable<int> idEquipe)
    {

        var idEquipeParameter = idEquipe.HasValue ?
            new ObjectParameter("IdEquipe", idEquipe) :
            new ObjectParameter("IdEquipe", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RencontresDuneEquipe_Result>("RencontresDuneEquipe", idEquipeParameter);
    }

}

}

