
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EF_MAJ_CHAMPIONNAT
{

using System;
    using System.Collections.Generic;
    
public partial class RENCONTRES
{

    public int ID_RENCONTRE { get; set; }

    public int ID_EQUIPE_RECEVOIR { get; set; }

    public int ID_EQUIPE_VISITER { get; set; }

    public string SCORELOCAUX { get; set; }

    public string SCOREVISITEURS { get; set; }



    public virtual EQUIPES EQUIPES { get; set; }

    public virtual EQUIPES EQUIPES1 { get; set; }

}

}
