//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enregistrement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Enregistrement()
        {
            this.Composition_Disque = new HashSet<Composition_Disque>();
            this.Diriger = new HashSet<Diriger>();
            this.Interpréter = new HashSet<Interpréter>();
            this.Abonné = new HashSet<Abonné>();
        }
    
        public int Code_Enregistrement { get; set; }
        public string Titre { get; set; }
        public string Nom_de_Fichier { get; set; }
        public string Durée { get; set; }
        public Nullable<int> Durée_Seconde { get; set; }
        public Nullable<decimal> Prix { get; set; }
        public Nullable<int> Code_Composition { get; set; }
    
        public virtual Composition Composition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Composition_Disque> Composition_Disque { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Diriger> Diriger { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Interpréter> Interpréter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Abonné> Abonné { get; set; }
    }
}
